package com.limoz.fleet.reporting.export;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Format-independent tabular report: a title, optional metadata (filters, generated by/at), column headers
 * and rows. Exporters render it as CSV, Excel or PDF; the JSON representation is returned as-is.
 */
public record ReportTable(
        String code,
        String title,
        Map<String, String> metadata,
        List<Column> columns,
        List<List<Object>> rows,
        List<Object> totals) {

    public record Column(String key, String label, Align align) {
        public static Column text(String key, String label) {
            return new Column(key, label, Align.LEFT);
        }

        public static Column number(String key, String label) {
            return new Column(key, label, Align.RIGHT);
        }
    }

    public enum Align { LEFT, RIGHT, CENTER }

    public static Builder builder(String code, String title) {
        return new Builder(code, title);
    }

    public static final class Builder {
        private final String code;
        private final String title;
        private final Map<String, String> metadata = new java.util.LinkedHashMap<>();
        private final List<Column> columns = new ArrayList<>();
        private final List<List<Object>> rows = new ArrayList<>();
        private List<Object> totals;

        private Builder(String code, String title) {
            this.code = code;
            this.title = title;
        }

        public Builder meta(String key, Object value) {
            if (value != null) metadata.put(key, String.valueOf(value));
            return this;
        }

        public Builder column(Column column) {
            columns.add(column);
            return this;
        }

        public Builder text(String key, String label) {
            return column(Column.text(key, label));
        }

        public Builder number(String key, String label) {
            return column(Column.number(key, label));
        }

        public Builder row(Object... values) {
            rows.add(new ArrayList<>(java.util.Arrays.stream(values).map(v -> v == null ? "" : v).toList()));
            return this;
        }

        public Builder rowNullable(List<Object> values) {
            rows.add(new ArrayList<>(values));
            return this;
        }

        public Builder totals(Object... values) {
            totals = new ArrayList<>(java.util.Arrays.stream(values).map(v -> v == null ? "" : v).toList());
            return this;
        }

        public ReportTable build() {
            return new ReportTable(code, title, metadata, List.copyOf(columns), List.copyOf(rows), totals);
        }
    }
}
