package com.limoz.fleet.audit.domain;

public enum AuditAction {
    CREATE, UPDATE, DELETE, ARCHIVE, RESTORE,
    STATUS_CHANGE, ASSIGN, UNASSIGN, APPROVE, REJECT, CANCEL, COMPLETE,
    LOGIN, LOGIN_FAILED, LOGOUT, PASSWORD_CHANGE, PASSWORD_RESET, ROLE_CHANGE, ENABLE, DISABLE,
    IMPORT, EXPORT, CORRECTION, SYSTEM
}
